# Generated by Django 4.0.1 on 2022-01-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marcasvehiculos',
            new_name='marcasvehiculo',
        ),
        migrations.RenameModel(
            old_name='vendedor',
            new_name='vendedore',
        ),
        migrations.RenameModel(
            old_name='ventas',
            new_name='venta',
        ),
    ]
